FROM python:3.11-slim
WORKDIR /app

COPY requirements-inference.txt .
RUN pip install --no-cache-dir -r requirements-inference.txt

COPY . .

ENV MODEL_DIR=/app
EXPOSE 8000
CMD ["uvicorn", "inference_onnx:app", "--host", "0.0.0.0", "--port", "8000"]
